### ISSUE TITLE
About the license 

### ISSUE THREAD

**Issue by eddie94** [athglentis/feather#2]
Hello I saw your paper and thought it is very useful and I thank you for your hard work.
However, I don't see any license specification in your repository.
Could you kindly tell me which license you used, if this code can be commercially used or any kind of information how to mention this project?
Thank you.

**Comment by athglentis** [comment]
Hello, thank you for your interest in our paper. I added the MIT license in the project's repository. To mention this project please use the citation provided in the README file. Thanks!
